# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Smbxfer
version:      0.01
version_from: lib/App/Smbxfer.pm
installdirs:  site
requires:
    Exporter:                      0
    File::Find:                    0
    File::Temp:                    0
    Filesys::SmbClient:            0
    Getopt::Long:                  0
    IO::Prompt:                    0
    Test::Differences:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
